##on:
##  pull_request:
##    types:
##      - closed

on:
  push:
    branches:
      - master


jobs:
  merged:
##    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - run: curl -sku ${{ secrets.JENKINS_B_SECRET }} ${{ secrets.JENKINS_URL_SECRET }}
