##on:
##  pull_request:
##    types:
##      - closed

on:
  push:
    branches:
      - master


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: curl --request GET --url https://jenkins.motaba.net/job/SpeedTest%20-%20Maven%20Project/build?token=speedtest
