on:
##  pull_request:
##    types:
##      - closed
  push:
    branches:
      - master

jobs:
  deploy:
##    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: curl -su ${{ secrets.JENKINS_B_SECRET }} ${{ secrets.JENKINS_URL_SECRET }}
